name: CHANGELOG
on:
  push:
    branches:
      - dev

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to publish tags & update release notes
      issues: write # Allows semantic-release to open issues
      pull-requests: write # Allows semantic-release to manage PR comments
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v6
        with:
          semantic_version: 19.0.5 # Recommended
          extra_plugins: |
            @semantic-release/changelog@6.0.0
